name: Map3 Telemetry Client

on: [push]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  map3-telemetry-release:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 14.x
          yarn-version: 3.2.2

      - run: yarn install

      - name: Dependencies audit
        run: npm audit

      - name: Build
        run: yarn build

      - name: Format check
        run: yarn format:check

      - name: Lint check
        run: yarn lint:check

      - name: Spell check
        run: yarn spell:check

      - name: Test
        run: yarn test

      - name: Setup test
        run: yarn test:setup

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
